@tool
extends SceneTree

# Phase 0 emits the documented text scene format with stable resource/node IDs.
# Node IDs introduced in Godot 4.6 are otherwise regenerated by PackedScene.pack.
func _initialize() -> void:
    var directory := "res://game/scenes"
    var error := DirAccess.make_dir_recursive_absolute(directory)
    if error != OK:
        push_error("Cannot create scene directory: %s" % error_string(error))
        quit(1)
        return
    for scene_name: String in ["boot", "lobby", "match", "replay"]:
        var digest := ("rts/scenes/" + scene_name).sha256_text()
        var uid := ResourceUID.id_to_text(digest.substr(0, 15).hex_to_int())
        var node_id := digest.substr(0, 7).hex_to_int()
        var path := "%s/%s.tscn" % [directory, scene_name]
        var output := FileAccess.open(path, FileAccess.WRITE)
        if output == null:
            push_error("Cannot open %s: %s" % [path, error_string(FileAccess.get_open_error())])
            quit(1)
            return
        output.store_string('[gd_scene format=3 uid="%s"]\n\n[node name="%s" type="Node" unique_id=%d]\n' % [uid, scene_name.capitalize(), node_id])
        output.flush()
        error = output.get_error()
        output.close()
        if error != OK:
            push_error("Cannot write %s: %s" % [path, error_string(error)])
            quit(1)
            return
        print("Generated: " + path)
    quit(0)
