@tool
extends SceneTree

# Phase 0 emits the documented text scene format with stable resource/node IDs.
# Node IDs introduced in Godot 4.6 are otherwise regenerated by PackedScene.pack.
func _initialize() -> void:
    var directory := "res://game/scenes"
    var error := DirAccess.make_dir_recursive_absolute(directory)
    if error != OK:
        push_error("Cannot create scene directory: %s" % error_string(error))
        quit(1)
        return
    for scene_name: String in ["boot", "lobby", "match", "replay"]:
        var digest := ("rts/scenes/" + scene_name).sha256_text()
        var uid := ResourceUID.id_to_text(digest.substr(0, 15).hex_to_int())
        var node_id := digest.substr(0, 7).hex_to_int()
        var path := "%s/%s.tscn" % [directory, scene_name]
        var output := FileAccess.open(path, FileAccess.WRITE)
        if output == null:
            push_error("Cannot open %s: %s" % [path, error_string(FileAccess.get_open_error())])
            quit(1)
            return
        var content: String = '[gd_scene format=3 uid="%s"]\n\n[node name="%s" type="Node" unique_id=%d]\n' % [uid, scene_name.capitalize(), node_id]
        if scene_name == "match":
            content = '[gd_scene format=3 uid="%s"]\n\n[ext_resource type="Script" path="res://game/scripts/Bridge/MatchBridge.cs" id="1"]\n[ext_resource type="Script" path="res://game/scripts/View/SelectionController.cs" id="2"]\n\n[node name="Match" type="Node" unique_id=%d]\n\n[node name="Bridge" type="Node" parent="." unique_id=1001]\nscript = ExtResource("1")\n\n[node name="Selection" type="Node2D" parent="." unique_id=1002]\nscript = ExtResource("2")\n' % [uid,node_id]
        if scene_name == "match":
            var resources := '[ext_resource type="Script" path="res://game/scripts/View/WorldRenderer.cs" id="3"]\n[ext_resource type="Script" path="res://game/scripts/View/RtsCamera.cs" id="4"]\n[ext_resource type="Environment" path="res://game/assets/generated/world_environment.tres" id="5"]\n[ext_resource type="Script" path="res://game/scripts/View/RenderBenchmark.cs" id="6"]\n\n'
            content=content.replace('[node name="Match"',resources+'[node name="Match"')
            content+='\n[node name="Renderer" type="Node3D" parent="." unique_id=1003]\nscript = ExtResource("3")\n\n[node name="Camera" type="Camera3D" parent="." unique_id=1004]\nscript = ExtResource("4")\n\n[node name="Environment" type="WorldEnvironment" parent="." unique_id=1005]\nenvironment = ExtResource("5")\n\n[node name="Sun" type="DirectionalLight3D" parent="." unique_id=1006]\nrotation_degrees = Vector3(-55,-30,0)\nlight_color = Color(0.9,0.93,1,1)\nlight_energy = 1.0\n\n[node name="Benchmark" type="Node" parent="." unique_id=1007]\nscript = ExtResource("6")\n'
        if scene_name == "match":
            content=content.replace('[node name="Match"','[ext_resource type="PackedScene" path="res://game/scenes/hud.tscn" id="7"]\n\n[node name="Match"')
            content+='\n[node name="HUD" parent="." unique_id=1008 instance=ExtResource("7")]\n'
        if scene_name == "boot":
            content=content.replace('[node name="Boot"','[ext_resource type="Script" path="res://game/scripts/UI/BootMenu.cs" id="1"]\n\n[node name="Boot"')
            content+='script = ExtResource("1")\n'
        output.store_string(content)
        output.flush()
        error = output.get_error()
        output.close()
        if error != OK:
            push_error("Cannot write %s: %s" % [path, error_string(error)])
            quit(1)
            return
        print("Generated: " + path)
    quit(0)
